FROM node:20-alpine

WORKDIR /app

RUN corepack enable

RUN apk add --no-cache python3 make g++

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

ENV NODE_ENV=development

ENV PORT=5000

EXPOSE ${PORT}

CMD ["pnpm", "dev:server"]